### ISSUE TITLE
Add the ability to add a prefix

### ISSUE THREAD

**Issue by ihard** [avito-tech/bioyino#15]
Select a list of metrics for example by the regular expression

**Comment by Albibek** [comment]
Could you please explain, what do you mean here. I'm not sure I understand.

**Comment by ihard** [comment]
The ability to add a prefix to the metrics that are sent to the carbon, example
statsd:
host.app.count

prefix:
dc1

to carbon:
dc1.host.app.count

**Comment by Albibek** [comment]
Such option already exists: https://github.com/avito-tech/bioyino/blob/master/config.toml#L19

**Comment by ihard** [comment]
Sorry, missed this line in the config.
Thank you!

**Comment by Albibek** [comment]
What you are asking here can be done by using https://github.com/grobian/carbon-c-relay. As of now we also use it for routing metrics between carbon backends and also for some regexp-based filtering/renaming. 
Please, do not count this message as a refusal to implement the requested feature in bioyino, but only as an advice to work problem around fast.
