### ISSUE TITLE
Better parsing sampled metrics

### ISSUE THREAD

**Issue by lexore** [avito-tech/bioyino#23]
For now bioyino parse sample rate as "all from @ to '\n' symbol" [here](https://github.com/avito-tech/bioyino/blob/master/src/parser.rs#L77).
It works with many metrics with '\n' delimiter in one packet.
But doen't work with one metric per packet.
With one metric per packet all metrics look like one long string without '\n' symbols.
And parsing "all from @ to '\n' symbol" doesn't parse it right.

Can you please fix parsing to expect float after "@"?

**Comment by Albibek** [comment]
Fixed in https://github.com/avito-tech/bioyino/commit/37fe6c2003ba8663c4ff1155864fbcf08570d310
