### ISSUE TITLE
Feature request: count per sec for metrics with "ms" type

### ISSUE THREAD

**Issue by lexore** [avito-tech/bioyino#35]
Hello.
For metrics "XXX" with type "ms" bioyino generate metric "XXX.count".
It send to carbon pure count of recieved packets every "interval" miliseconds.
"interval" - setting from config file.
I use it for get "packet per second" value this way: `scale(XXX.count, 0.1)` (i have interval = 10000).
I ask to create another metric - count_ps (float) with value = count * 1000 / interval (from config).
With it will no need to use "scale" for every "pps" metric.
I think, it will be very usefull and handy - easy way to get "packets per second" value.

**Comment by msaf1980** [comment]
https://github.com/avito-tech/bioyino/issues/37
I don't know Rust, so realized throw unsafe.

**Comment by Albibek** [comment]
Closing this as a duplicate of #37. The rate feature will be added in 0.8.0
