### ISSUE TITLE
Feature request: allow change naming scheme for compability with different statsd implementations

### ISSUE THREAD

**Issue by msaf1980** [avito-tech/bioyino#38]
Different realization of StatsD has different naming scheme

Add option for rename some names with regex or simple string pattern, like

{ 
  "^percentile\." = "p", 
  "^min$" = "lower", 
  "^max$" = "upper"
}

**Comment by ihard** [comment]
+ 100500

**Comment by Albibek** [comment]
This is solved in 0.6.0. See config.toml or CHANGELOG for details
