### ISSUE TITLE
Replication and raft clients on node with several interfaces

### ISSUE THREAD

**Issue by msaf1980** [avito-tech/bioyino#40]
Add options to bind client sockets for replication and raft to specific IP.

**Comment by Albibek** [comment]
When specifying raft nodes, you can use `this-node` parameter to set such binding.

**Comment by msaf1980** [comment]
It does not solve. Client socket for raft thread (and may be replication too) not bind to specified address
TcpStream::connect not do this, instead of TcpStream::connect_std with custom stream. created and binded with net2::TcpBuilder
https://github.com/Albibek/raft-tokio/blob/master/src/tcp.rs#L219

**Comment by msaf1980** [comment]
Good news ! I try to add this feature (in  raft-tokio and bioyino).
Socket was binding to correct address, and work as planned.
But leader election don't work without any errors in log (cluster split brain with many master). And at this time I don't undestand  why.
https://github.com/msaf1980/raft-tokio/commits/master
https://github.com/msaf1980/bioyino/tree/statsite-bind

**Comment by Albibek** [comment]
Try enabling trace log in bioyino/raft-tokio. Raft-tokio logs almos every fail there

**Comment by Albibek** [comment]
You can also try running `cargo test -- --nocapture` with changed raft-tokio, it will print trace logs by default

**Comment by msaf1980** [comment]
Hello. I patched raft-tokio and bioyino for this.

https://github.com/Albibek/raft-tokio/pull/2
https://github.com/avito-tech/bioyino/pull/43

**Comment by Albibek** [comment]
The vesion with an client-bind option is in 0.5.0 branch. Can you test it please?

**Comment by Albibek** [comment]
The binding of raft protocol client is in 0.5.0 branch.

**Comment by msaf1980** [comment]
For carbon client - may be in some cases, but it's not necessary for our environment
