### ISSUE TITLE
Valid example config

### ISSUE THREAD

**Issue by ihard** [avito-tech/bioyino#44]
The current example of the config is incorrect by 50 percent. 
Can you give the minimum working config for building from the master?
Maybe there is a key in to generate a configuration example?
An interesting option with raft protocol.

**Comment by Albibek** [comment]
The master is currently kind of old. I recommend to use 0.5.0 branch at this moment. It's going to master soon, I think. You'll find a new, more detailed config, there. What setup do you need for the example? Single node with low amount of metrics?

**Comment by ihard** [comment]
Thank you, branch did not guess to look.
Config for three nodes with raft.

**Comment by Albibek** [comment]
Pushed an example for 3 nodes
https://github.com/avito-tech/bioyino/blob/v0.5.0/examples/cluster.toml
