### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by jah-jh** [avito-tech/bioyino#52]
Hi
I see that there is another  issue about log to file (#28)
I also found this feature it useful in prod.

How you resolve this in your env?

**Comment by Albibek** [comment]
We currently run it with supervisord. It captures stdout and stderr. The right way would be writing to syslog, which will forward data to file and handle rotation. I'm not planning to implement direct file logging atm, but will implement syslog logging eventually.

**Comment by jah-jh** [comment]
You are right.
Using Syslog is the best approach. Will be good to have this functionality.

**Comment by jah-jh** [comment]
Closed

**Comment by Albibek** [comment]
The syslog logging has beed added into 0.7.0 release.
